imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    - { resource: services.yml }

    # Mopa Bootstrap
    - { resource: mopa/mopa_bootstrap.yml }

    # FriendOfSymfony Bundles
    #- { resource: fos/fos_comment.yml }
#    - { resource: fos/fos_rest.yml }
    - { resource: fos/fos_user.yml }
    #- { resource: fos/fos_elastica.yml }
#    - { resource: fos/fos_message.yml }

  # Sonata Core Bundles
    - { resource: sonata/sonata_block.yml }
#    - { resource: sonata/sonata_formatter.yml }
#    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_seo.yml }
#    - { resource: sonata/sonata_timeline.yml }
#    - { resource: sonata/sonata_intl.yml }
    - { resource: sonata/sonata_core.yml }
#    - { resource: sonata/sonata_user.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    form:
        resources:
            - 'bootstrap_3_layout.html.twig'
#            - 'SonataFormatterBundle:Form:formatter.html.twig'
#            - 'SonataMediaBundle:Form:media_widgets.html.twig'
#            - 'SonataCoreBundle:Form:datepicker.html.twig'
#            - 'ChamiloCoreBundle:Form:fields.html.twig'

#    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

    paths:
          "%kernel.root_dir%/../src/Chamilo/CoreBundle/Resources/views/default": template_style

    globals:
          show_toolbar: true
          show_footer: true
          software_name: Chamilo
          version: 2
          session_teachers:
          teachers:
          news_counter:
          news_list:
          messages_count:
          message_link:
          is_profile_editable:
          administrator_name:
          plugin_footer_left:
          plugin_footer_center:
          plugin_content_bottom:
          plugin_header_left:
          plugin_header_center:
          plugin_header_right:
          plugin_header_main:
          plugin_menu_bottom:
          plugin_menu_top:
          plugin_content_top:
          plugin_footer_right:
          footer_extra_content:
          course_session_block:
          show_course_shortcut:
          show_course_navigation_menu:
          actions:
          header:
          message:
          welcome_to_course_block:

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                # if using pdo_sqlite as your database driver:
                #   1. add the path in parameters.yml
                #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
                #   2. Uncomment database_path in parameters.yml.dist
                #   3. Uncomment next line:
                #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        # auto_mapping: true
        entity_managers:
            default:
                auto_mapping: true
                mappings: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_migrations:
    dir_name: %kernel.root_dir%/Migrations/Schema/V20/
    namespace: Application\Migrations\Schema\V20
    table_name: version
    name: Chamilo Migrations

# Platform settings

sylius_settings:
    driver: doctrine/orm
    classes:
        parameter:
            model: Chamilo\CoreBundle\Entity\SettingsCurrent
            repository: Chamilo\CoreBundle\Entity\Repository\SettingsCurrentRepository

# Course settings
chamilo_course:
    driver: doctrine/orm
    classes:
        parameter:
            model: Chamilo\CourseBundle\Entity\CCourseSetting
            repository: Chamilo\CourseBundle\Entity\Repository\CCourseSettingRepository

doctrine_cache:
    providers:
        sylius_settings:
            type: file_system
        chamilo_settings:
            type: file_system

# Bower configuration
sp_bower:
    bin: "%sp_bower_bin%" # Optional
    assetic: true
    install_on_warmup: false
    bundles:
        ChamiloThemeBundle:
            cache:
                directory: %kernel.root_dir%/cache/public/components/cache

stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            tree: true
            timestampable: true
            sluggable: true
            sortable: true

liip_theme:
    themes: ['web', 'tablet', 'phone']
    active_theme: 'web'
    assetic_integration: true

oneup_flysystem:
    adapters:
        local.adapter:
            local:
                directory: %kernel.root_dir%/courses
#        s3.adapter:
#              awss3v3:
#                  client: s3_client # add service "s3_client"
#                  bucket: ~
#                  prefix: ~

    filesystems:
        course:
            adapter: local.adapter
            cache: ~
            alias: ~
            mount: ~

ivory_ck_editor:
    autoload: false
    base_path: "bundles/ivoryckeditor"
    js_path:   "bundles/ivoryckeditor/ckeditor.js"
    default_config: default
    plugins:
        wordcount:
            path:     "/bundles/chamilocore/ckeditor/plugins/wordcount"
            filename: "plugin.js"
#        adobeair:
#            path:     "/bundles/chamilotheme/components/ckeditor/plugins/adobeair"
#            filename: "plugin.js"
#        iframedialog:
#            path:     "/bundles/chamilotheme/components/ckeditor/plugins/iframedialog"
#            filename: "plugin.js"
#        docprops:
#            path:     "/bundles/chamilotheme/components/ckeditor/plugins/docprops"
#            filename: "plugin.js"
#

#jms_translation:
#    configs:
#        app:
#            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
#            output_dir: %kernel.root_dir%/Resources/translations
#            ignored_domains: [routes]
#            excluded_names: ["*TestCase.php", "*Test.php"]
#            excluded_dirs: [cache, data, logs]
##            extractors: [alias_of_the_extractor]


