#index:
#    path: /

#login:
#    path: /login

logout:
    path: /logout

chamilo_course:
    resource: "@ChamiloCourseBundle/Resources/config/routing.yml"
    prefix:   /

_front:
    resource: routing_front.yml

chamilo_installer:
    resource: "@ChamiloInstallerBundle/Resources/config/routing.yml"

# Always at the end
core_bundle:
    resource: "@ChamiloCoreBundle/Resources/config/routing.yml"

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
