Chamilo\CmsBundle\Document\Page:
    uri_schema: /page/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

Symfony\Cmf\Bundle\BlogBundle\Doctrine\Phpcr\Blog:
    uri-schema: /blogs/{blog}
    token_providers:
            blog: [content_method, { method: getName }]

Symfony\Cmf\Bundle\BlogBundle\Doctrine\Phpcr\Post:
    uri-schema: /blogs/{blog}/{date}/{title}
        token_providers:
            blog: [content_method, { method: getBlog }]
            date: [content_datetime, { method: getDate }]
            title: [content_method, { method: getTitle }]

#Chamilo\CmsBundle\Document\Post:
#    uri_schema: /post/{date}/{title}
#    token_providers:
#        date: [content_datetime, { method: getPublishStartDate }]
#        title: [content_method, { method: getTitle }]
