services:
    sonata.admin.user_field:
        class: Chamilo\UserBundle\Admin\UserField
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "UserField" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\UserField
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.user_field_values:
        class: Chamilo\UserBundle\Admin\UserFieldValuesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "UserFieldValues" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\UserFieldValues
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]