index:
    resource: "@ChamiloCoreBundle/Controller/IndexController.php"
    type:     annotation
    prefix:   /

userportal:
    resource: "@ChamiloCoreBundle/Controller/UserPortalController.php"
    type:     annotation
    prefix:   /userportal

user:
    resource: "@ChamiloCoreBundle/Controller/User/UserController.php"
    type:     annotation
    prefix:   /user

course:
    resource: "@ChamiloCoreBundle/Controller/CourseController.php"
    type:     annotation
    prefix:   /course


legacy_javascript:
    resource: "@ChamiloCoreBundle/Controller/JavascriptLegacyController.php"
    type:     annotation
    prefix:   /js

# Legacy routes
main:
    path: /main/{name}
    defaults: { _controller: ChamiloCoreBundle:Legacy:classic }
    requirements:
      name: .+

# web url shortcuts for legacy templates
web.ajax:
    path: main/inc/ajax/

web.main:
    path: main/

web.img:
    path: bundles/chamilocore/img/

# Core controllers

core_admin:
    resource: "@ChamiloCoreBundle/Controller/Admin"
    type: annotation
    prefix:   /admin

#core_app:
#    resource: "@ChamiloCoreBundle/Controller/App"
#    type: annotation
#    prefix:   /app

course_url:
    path: courses

core_tool:
    resource: "@ChamiloCourseBundle/Controller"
    type: annotation
    prefix: /courses/{course}/


core_tool_document:
    pattern: /courses/{course}/document/{file}
    defaults:
        _controller: ChamiloCoreBundle:Index:getDocument
    requirements:
        file: .+ # allow "/" in {file}

# redirects /url/ to /url
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: ChamiloCoreBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
        _method: GET

## Portal settings
chamilo_platform_settings_list:
    pattern: /settings
    defaults:
        _controller: ChamiloSettingsBundle:Settings:index
        template: ChamiloSettingsBundle:Settings:index.html.twig
#
chamilo_platform_settings:
    pattern: /settings/{namespace}
    defaults:
        _controller: ChamiloSettingsBundle:Settings:update
        template: ChamiloSettingsBundle:Settings:default.html.twig
#
## Course settings
chamilo_course_settings:
    pattern: /courses/{course}/settings/{namespace}
    defaults:
        _controller: ChamiloCourseBundle:Settings:update
        template: ChamiloCourseBundle:Settings:default.html.twig
#
chamilo_course_tool_index:
    pattern: courses/{course}/tools
    methods: [GET, POST, HEAD, DELETE]
    defaults:
        _controller: chamilo_course.controller.tool:indexAction
